# This docker-compose file is meant to be run from the Docker/ directory
services:
  allama:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    ports:
      - "11435:11435"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs  # Mount logs directory
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - PORT=11435
      - DATABASE_PATH=/app/data/allama.db
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"