version: '3.8'

# This docker-compose file is meant to be run from the Docker/ directory
services:
  allama:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    ports:
      - "11435:11435"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=11435
      - DATABASE_PATH=/app/data/allama.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OLLAMA_HOST=${OLLAMA_Host:-http://localhost:11434}
    restart: unless-stopped
